PHEE-477 Create an orb that fetches the docker images and do helm upgrade

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -82,6 +82,13 @@ jobs:
           command: |
             ./gradlew bootJar
             docker build -t openmf/ph-ee-integration-test:latest .
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
+              docker image tag openmf/ph-ee-integration-test:latest openmf/ph-ee-integration-test:$JIRA_STORY
+            fi
 
       # Log in to DockerHub using environment variables
       - run:
@@ -91,41 +98,16 @@ jobs:
       # Push the Docker image to DockerHub
       - run:
           name: Push Docker image to DockerHub
-          command: docker push openmf/ph-ee-integration-test:latest
-
-  upgrade-helm-chart:
-    docker:
-      - image: cimg/python:3.10
-    parameters:
-      cluster-name:
-        description: "sit"
-        type: string
-      recreate-pods: 
-          default: true
-          type: boolean
-      wait:
-          default: true
-          type: boolean
-    steps:
-      - aws-eks/update-kubeconfig-with-authenticator:
-          cluster-name: "sit"
-          aws-region: "$REGION"
-      - helm/upgrade-helm-chart:
-          chart: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin/ph-ee-g2psandbox-fynarfin-0.2.0.tgz"
-          release-name: g2p-sandbox
-          namespace: paymenthub
-          recreate-pods: true
-          add-repo: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin"
-          wait: true
-          timeout: "300s"
-          #- run: helm test g2p-sandbox --namespace=paymenthub
-          # reset-values: true
-          # dry-run: true
-      # - helm/install-helm-chart:
-      #     add-repo: "https://fynarfin.io/images/"
-      #     chart: "https://fynarfin.io/images/ph-ee-g2psandbox-0.2.0.tgz"
-      #     release-name: g2p-sandbox
-      #     namespace: ph-test
+          command: |
+            if [ "$CIRCLE_BRANCH" = "master" ]; then
+            docker push openmf/ph-ee-integration-test:latest
+            fi
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+            PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+            PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+            JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+            docker push openmf/ph-ee-integration-test:${JIRA_STORY}
+            fi
 
   create-secret-paymenthub-namespace:
     docker:
@@ -227,17 +209,25 @@ workflows:
       - build_and_push_latest_image:
           context:
             - DOCKER
-      - upgrade-helm-chart:
-          cluster-name: sit
+      - mifos-orb/docker-image-availability-check-and-upgrade:
+          namespace: paymenthub
+          chart: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin/ph-ee-g2psandbox-fynarfin-0.2.0.tgz"
+          release-name: g2p-sandbox
+          add-repo: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin"
+          cluster-name: "sit"
+          aws-region: "$REGION"
+          service-file-path: https://raw.githubusercontent.com/openMF/ph-ee-env-labs/master/.circleci/services.txt
+          context:
+            - AWS
+            - Helm
+            - slack
           requires:
             - build
             - build_and_push_tag_image
             - build_and_push_latest_image
-          context:
-            - AWS
       - create-secret-paymenthub-namespace:
           requires:
-            - upgrade-helm-chart
+            - mifos-orb/docker-image-availability-check-and-upgrade
           context:
             - AWS
             - Helm
@@ -251,7 +241,7 @@ workflows:
       #       - install-helm-chart
       - test-chart-gov:
           requires:
-            - upgrade-helm-chart
+            - mifos-orb/docker-image-availability-check-and-upgrade
             - create-secret-paymenthub-namespace
           context:
             - AWS
@@ -260,7 +250,7 @@ workflows:
             - Ngrok
       - test-chart-ams:
           requires:
-            - upgrade-helm-chart
+            - mifos-orb/docker-image-availability-check-and-upgrade
             - create-secret-paymenthub-namespace
           context:
             - AWS
